### ISSUE TITLE
Will the zettel notes source code be made available?

### ISSUE THREAD

**Issue by ln-12** [damionx7/Zettel-Notes-Documentation#1]
Hey, I discovered the zettel notes app which seems to be awesome! I wondered if the source code will be made available. Do you have any plans to do so?

**Comment by damionx7** [comment]
Thanks for the kind words. Maybe in future when I will no longer be able to support development of ZN i will make the app open source

**Comment by rokejulianlockhart** [comment]
I actually don't think it'll do any harm at all. Consider KDE's Krita – they always submit it as costing about £15 to app stores, which is a darn lot for software nowadays, bit people almost always purchase it anyway instead of build it from source. They buy it because of the functionality.

I honestly don't think that open-sourcing would cause anything bad. I think it would allow others to help maintain it is all, and it's not like the extensions need to be open-sourced too, so the above is already moot anyway.
